from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
import re
import uuid

app = FastAPI(title="Agri / WC Calculator")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def health():
    return {
        "Application": "Agri / WC Calculator",
        "Status": "Professional Underwriting Engine Running"
    }

# ---------------- PARSER ----------------

def extract_amount(text, keywords):
    for key in keywords:
        pattern = rf"{key}[^0-9]*([\d,]+(?:\.\d+)?)"
        match = re.search(pattern, text.lower())
        if match:
            return float(match.group(1).replace(",", ""))
    return 0

# ---------------- FINANCIAL ENGINE ----------------

def compute_metrics(data):

    sales = data["sales"]
    profit = data["profit"]
    depreciation = data["depreciation"]
    interest = data["interest"]
    inventory = data["inventory"]
    debtors = data["debtors"]
    creditors = data["creditors"]
    emi = data["emi"]

    current_assets = inventory + debtors
    current_liabilities = creditors

    nwc = current_assets - current_liabilities
    current_ratio = current_assets / current_liabilities if current_liabilities else 0
    mpbf = (0.75 * current_assets) - current_liabilities
    wc_limit = sales * 0.20 if sales else 0

    ebitda = profit + depreciation + interest
    annual_obligation = emi * 12 if emi else 1
    dscr = ebitda / annual_obligation if annual_obligation else 0

    agri_limit = ((profit * 0.60) / 12) / 0.14 if profit else 0

    return {
        "NWC": nwc,
        "Current_Ratio": current_ratio,
        "MPBF": mpbf,
        "WC_Limit": wc_limit,
        "EBITDA": ebitda,
        "DSCR": dscr,
        "Agri_Limit": agri_limit
    }

# ---------------- RISK ENGINE ----------------

def risk_engine(metrics):

    score = 100
    flags = []

    if metrics["Current_Ratio"] < 1:
        score -= 25
        flags.append("Weak liquidity position")

    if metrics["DSCR"] < 1.2:
        score -= 25
        flags.append("Debt servicing stress")

    if metrics["NWC"] < 0:
        score -= 15
        flags.append("Negative working capital")

    if metrics["EBITDA"] <= 0:
        score -= 20
        flags.append("Negative operating profitability")

    classification = (
        "Low Risk" if score >= 80 else
        "Moderate Risk" if score >= 60 else
        "High Risk"
    )

    return score, classification, flags

# ---------------- AI NARRATIVE ----------------

def generate_narrative(metrics, risk_class):

    return f"""
    Current Ratio: {round(metrics['Current_Ratio'],2)}
    Net Working Capital: {round(metrics['NWC'],2)}
    DSCR: {round(metrics['DSCR'],2)}
    MPBF Eligibility: {round(metrics['MPBF'],2)}
    WC (20% Method): {round(metrics['WC_Limit'],2)}
    Agri Limit: {round(metrics['Agri_Limit'],2)}

    Overall Risk Classification: {risk_class}
    Generated by Agri / WC Calculator.
    """.strip()

# ---------------- MAIN API ----------------

@app.post("/analyze")
async def analyze(
    bs_file: UploadFile = File(...),
    pl_file: UploadFile = File(...)
):

    case_id = str(uuid.uuid4())[:8]

    bs_text = (await bs_file.read()).decode(errors="ignore")
    pl_text = (await pl_file.read()).decode(errors="ignore")

    financials = {
        "sales": extract_amount(pl_text, ["sales","turnover"]),
        "profit": extract_amount(pl_text, ["net profit"]),
        "depreciation": extract_amount(pl_text, ["depreciation"]),
        "interest": extract_amount(pl_text, ["interest"]),
        "inventory": extract_amount(bs_text, ["inventory","stock"]),
        "debtors": extract_amount(bs_text, ["debtors"]),
        "creditors": extract_amount(bs_text, ["creditors"]),
        "emi": extract_amount(pl_text, ["emi"])
    }

    metrics = compute_metrics(financials)
    risk_score, risk_class, flags = risk_engine(metrics)
    narrative = generate_narrative(metrics, risk_class)

    return {
        "Case_ID": case_id,
        "Financials": financials,
        "Metrics": metrics,
        "Risk_Score": risk_score,
        "Risk_Class": risk_class,
        "Fraud_Flags": flags,
        "AI_Narrative": narrative
    }
